/**
 * Phase 1 cross-tradition sacred-text catalog.
 *
 * These records are metadata, study links, and Mindvanta-original prompts.
 * Full primary-text bodies should only be added through reviewed TextVersion rows.
 */

import type { DifficultyBand, LicenseStatus, TextVersion, TextWork } from '../types';

type PhaseOneWorkSeed = {
  slug: string;
  title: string;
  alternateTitles?: string[];
  author: string;
  tradition: string;
  genre: TextWork['genre'];
  approxDate: string;
  difficulty: TextWork['difficulty'];
  difficultyBand: DifficultyBand;
  summary: string;
  why: string;
  licenseStatus: LicenseStatus;
  sourceLicenseStatus: TextWork['source_license_status'];
  availabilityMode: TextWork['availability_mode'];
  contentType: NonNullable<TextWork['contentType']>;
  sourceName: string;
  sourceUrl?: string;
  publicationYear?: number | string;
  originalLanguage: string;
  themes: string[];
  tags: string[];
  courseSlug: string;
  moduleSlug: string;
  courseReason: string;
  reviewStatus?: NonNullable<TextWork['reviewStatus']>;
  warning?: string;
};

const phaseOneSeeds: PhaseOneWorkSeed[] = [
  {
    slug: 'yoga-vasistha',
    title: 'Yoga Vasistha',
    alternateTitles: ['Yoga-Vasishtha Maharamayana'],
    author: 'Tradition: attributed to Valmiki; English translation associated with Vihari-Lala Mitra',
    tradition: 'Advaita Vedanta',
    genre: 'philosophical_treatise',
    approxDate: 'medieval Sanskrit source; 19th century English translation',
    difficulty: 5,
    difficultyBand: 'advanced',
    summary: 'A vast nondual teaching cycle on mind-created worlds, dreamlike reality, and liberation through insight.',
    why: 'It directly serves Mindvanta themes of illusion, witnessing, dreams, and the freedom that comes from seeing the mind clearly.',
    licenseStatus: 'public_domain_us',
    sourceLicenseStatus: 'pd',
    availabilityMode: 'excerpt',
    contentType: 'excerpt_collection',
    sourceName: 'Public-domain old translation / Project Gutenberg where available',
    originalLanguage: 'Sanskrit',
    themes: ['Dream Reality', 'Witness Consciousness', 'Mind Training', 'Liberation', 'Non-Attachment'],
    tags: ['advaita', 'dream', 'mind', 'witness', 'liberation'],
    courseSlug: 'reality-dream-and-mind',
    moduleSlug: 'the-dreamlike-world',
    courseReason: 'Primary source for the course arc on dreamlike reality and mind-projected worlds.',
  },
  {
    slug: 'upanishads-paramananda',
    title: 'The Upanishads',
    alternateTitles: ['Upanishads - Swami Paramananda Translation'],
    author: 'Ancient rishis; translated by Swami Paramananda',
    tradition: 'Vedanta',
    genre: 'philosophical_treatise',
    approxDate: 'ancient Sanskrit source; 1919 English publication',
    difficulty: 3,
    difficultyBand: 'intermediate',
    summary: 'Core Vedantic teachings on Atman, Brahman, deathlessness, inner light, and the awareness behind experience.',
    why: 'It gives beginners and returning practitioners a direct vocabulary for awareness before thought.',
    licenseStatus: 'public_domain_us',
    sourceLicenseStatus: 'pd',
    availabilityMode: 'root_text',
    contentType: 'excerpt_collection',
    sourceName: 'Project Gutenberg edition',
    sourceUrl: 'https://www.gutenberg.org/',
    publicationYear: 1919,
    originalLanguage: 'Sanskrit',
    themes: ['Awareness', 'Self-Inquiry', 'Witness Consciousness', 'Death and Rebirth', 'Silence'],
    tags: ['vedanta', 'self', 'brahman', 'atman', 'awareness'],
    courseSlug: 'what-is-awareness',
    moduleSlug: 'the-witness-behind-experience',
    courseReason: 'Foundation text for awareness, witness consciousness, and Atman/Brahman study.',
  },
  {
    slug: 'bhagavad-gita-song-celestial',
    title: 'Bhagavad Gita',
    alternateTitles: ['The Song Celestial'],
    author: 'Vyasa tradition; translated by Sir Edwin Arnold',
    tradition: 'Hinduism',
    genre: 'philosophical_treatise',
    approxDate: 'ancient Sanskrit source; 1885 English publication',
    difficulty: 2,
    difficultyBand: 'beginner',
    summary: 'A poetic rendering of the Gita on dharma, devotion, self-mastery, and action without attachment.',
    why: 'It bridges contemplative insight with daily obligation, courage, surrender, and disciplined action.',
    licenseStatus: 'public_domain_us',
    sourceLicenseStatus: 'pd',
    availabilityMode: 'root_text',
    contentType: 'excerpt_collection',
    sourceName: 'Project Gutenberg edition',
    sourceUrl: 'https://www.gutenberg.org/',
    publicationYear: 1885,
    originalLanguage: 'Sanskrit',
    themes: ['Devotion', 'Karma', 'Non-Attachment', 'Discipline', 'Courage'],
    tags: ['gita', 'dharma', 'bhakti', 'karma-yoga', 'surrender'],
    courseSlug: 'the-path-of-practice',
    moduleSlug: 'action-without-attachment',
    courseReason: 'Core support for practice in action, devotion, and non-attachment.',
  },
  {
    slug: 'yoga-sutras-johnston',
    title: 'Yoga Sutras of Patanjali',
    alternateTitles: ['Yoga Sutras - Charles Johnston Translation'],
    author: 'Patanjali; translated by Charles Johnston',
    tradition: 'Yoga',
    genre: 'sutra',
    approxDate: 'classical Sanskrit source; 1912 English publication',
    difficulty: 3,
    difficultyBand: 'intermediate',
    summary: 'A compact psychology of mind-waves, practice, dispassion, concentration, and samadhi.',
    why: 'It gives Mindvanta a rigorous meditation map that connects discipline with experiential stillness.',
    licenseStatus: 'public_domain_us',
    sourceLicenseStatus: 'pd',
    availabilityMode: 'root_text',
    contentType: 'excerpt_collection',
    sourceName: 'Project Gutenberg edition',
    sourceUrl: 'https://www.gutenberg.org/',
    publicationYear: 1912,
    originalLanguage: 'Sanskrit',
    themes: ['Mind Training', 'Practice', 'Stillness', 'Concentration', 'Liberation'],
    tags: ['yoga', 'meditation', 'samadhi', 'discipline', 'mind-waves'],
    courseSlug: 'the-path-of-practice',
    moduleSlug: 'yoga-as-stilling-the-mind',
    courseReason: 'Practical foundation for meditation, concentration, and stabilizing attention.',
  },
  {
    slug: 'dhammapada',
    title: 'Dhammapada',
    author: 'Buddhist tradition; public-domain English translators include Max Muller and F. L. Woodward',
    tradition: 'Buddhism',
    genre: 'compendium',
    approxDate: 'Pali canon source; public-domain English editions',
    difficulty: 1,
    difficultyBand: 'beginner',
    summary: 'Short ethical and contemplative verses on mind, craving, anger, wisdom, peace, and death.',
    why: 'Its concise verses are ideal for daily reflections and beginner-friendly mind training.',
    licenseStatus: 'public_domain_us',
    sourceLicenseStatus: 'pd',
    availabilityMode: 'root_text',
    contentType: 'excerpt_collection',
    sourceName: 'Project Gutenberg public-domain editions',
    sourceUrl: 'https://www.gutenberg.org/',
    originalLanguage: 'Pali',
    themes: ['Mind Training', 'Compassion', 'Non-Attachment', 'Death and Rebirth', 'Wisdom'],
    tags: ['buddhism', 'mindfulness', 'anger', 'desire', 'peace'],
    courseSlug: 'the-path-of-practice',
    moduleSlug: 'discipline-and-mind',
    courseReason: 'Concise training text for ethics, desire, anger, and wakefulness.',
  },
  {
    slug: 'diamond-sutra',
    title: 'Diamond Sutra',
    author: 'Mahayana Buddhist tradition; translated by William Gemmell',
    tradition: 'Mahayana Buddhism',
    genre: 'sutra',
    approxDate: 'Sanskrit source; 1912 English publication',
    difficulty: 4,
    difficultyBand: 'advanced',
    summary: 'A Mahayana sutra on emptiness, non-grasping, no fixed self, and compassionate action without clinging.',
    why: 'It pairs naturally with nondual themes while challenging the mind to release fixed conceptual reality.',
    licenseStatus: 'public_domain_us',
    sourceLicenseStatus: 'pd',
    availabilityMode: 'root_text',
    contentType: 'excerpt_collection',
    sourceName: 'Project Gutenberg edition',
    sourceUrl: 'https://www.gutenberg.org/',
    publicationYear: 1912,
    originalLanguage: 'Sanskrit / Chinese transmission',
    themes: ['Emptiness', 'Non-Attachment', 'No-self', 'Compassion', 'Formlessness'],
    tags: ['mahayana', 'emptiness', 'no-self', 'non-grasping', 'compassion'],
    courseSlug: 'emptiness-and-non-grasping',
    moduleSlug: 'the-diamond-sutra-and-no-fixed-self',
    courseReason: 'Primary text for emptiness, no fixed self, and non-grasping modules.',
  },
  {
    slug: 'vivekachudamani',
    title: 'Crest-Jewel of Wisdom',
    alternateTitles: ['Vivekachudamani'],
    author: 'Attributed to Shankara; translated by Charles Johnston',
    tradition: 'Advaita Vedanta',
    genre: 'philosophical_treatise',
    approxDate: 'traditional Sanskrit source; Johnston edition',
    difficulty: 4,
    difficultyBand: 'advanced',
    summary: 'A direct Advaita manual on discrimination, self-inquiry, witness consciousness, and liberation.',
    why: 'It turns nondual language into the daily work of discerning the real from the unreal.',
    licenseStatus: 'public_domain_us',
    sourceLicenseStatus: 'pd',
    availabilityMode: 'excerpt',
    contentType: 'excerpt_collection',
    sourceName: 'Charles Johnston edition; copyright renewal review noted by public sources',
    originalLanguage: 'Sanskrit',
    themes: ['Self-Inquiry', 'Witness Consciousness', 'Liberation', 'Renunciation', 'Real and Unreal'],
    tags: ['advaita', 'viveka', 'witness', 'renunciation', 'liberation'],
    courseSlug: 'what-is-awareness',
    moduleSlug: 'the-witness-behind-experience',
    courseReason: 'Supports direct self-inquiry and discrimination between the real and unreal.',
  },
  {
    slug: 'ashtavakra-gita',
    title: 'Ashtavakra Gita',
    author: 'Ashtavakra tradition; John Richards translation commonly presented as public domain',
    tradition: 'Advaita Vedanta',
    genre: 'philosophical_treatise',
    approxDate: 'Sanskrit source; modern public-domain-facing edition requires source verification',
    difficulty: 5,
    difficultyBand: 'advanced',
    summary: 'A radical Advaita text that points directly to awareness beyond identity, effort, and conceptual bondage.',
    why: 'It is one of the strongest Mindvanta sources for pure awareness, while needing careful framing.',
    licenseStatus: 'source_text_only',
    sourceLicenseStatus: 'original_only',
    availabilityMode: 'guided_study',
    contentType: 'reflection_source',
    sourceName: 'John Richards translation copies require final verification before full-text bundling',
    originalLanguage: 'Sanskrit',
    themes: ['Awareness', 'Non-Attachment', 'Witness Consciousness', 'Liberation', 'Stillness'],
    tags: ['advaita', 'awareness', 'non-identification', 'freedom', 'witness'],
    courseSlug: 'what-is-awareness',
    moduleSlug: 'awareness-without-identity',
    courseReason: 'Advanced pointer for awareness without identity and effortless freedom.',
    reviewStatus: 'approved',
    warning: 'Approved only for Mindvanta-original summaries and prompts until translation reuse is verified.',
  },
  {
    slug: 'avadhuta-gita',
    title: 'Avadhuta Gita',
    author: 'Dattatreya tradition; Kanoo Mal translation described as public domain in old-source collections',
    tradition: 'Advaita Vedanta',
    genre: 'philosophical_treatise',
    approxDate: 'Sanskrit source; 1920 English translation',
    difficulty: 5,
    difficultyBand: 'advanced',
    summary: 'An ecstatic radical nondual text on freedom beyond purity, impurity, identity, and limitation.',
    why: 'It broadens Mindvanta beyond clean philosophical nonduality into wild, vast, uncompromising freedom.',
    licenseStatus: 'source_text_only',
    sourceLicenseStatus: 'original_only',
    availabilityMode: 'guided_study',
    contentType: 'reflection_source',
    sourceName: 'Kanoo Mal translation source scan pending before full-text bundling',
    publicationYear: 1920,
    originalLanguage: 'Sanskrit',
    themes: ['Freedom', 'Nondual Identity', 'Vastness', 'Self beyond Form', 'Beyond Concepts'],
    tags: ['advaita', 'dattatreya', 'freedom', 'vastness', 'nonduality'],
    courseSlug: 'what-is-awareness',
    moduleSlug: 'awareness-without-identity',
    courseReason: 'Advanced companion for awareness beyond limitation and conceptual identity.',
    reviewStatus: 'approved',
    warning: 'Approved only for Mindvanta-original summaries and prompts until translation reuse is verified.',
  },
  {
    slug: 'devi-bhagavata-purana',
    title: 'Devi Bhagavata Purana',
    author: 'Vyasa tradition; Swami Vijnanananda translation requires reuse verification',
    tradition: 'Shakta',
    genre: 'compendium',
    approxDate: 'Sanskrit Purana; 1922 English translation',
    difficulty: 3,
    difficultyBand: 'intermediate',
    summary: 'A Shakta Purana centering the Divine Mother, cosmic power, devotion, protection, and grace.',
    why: 'It is a strong fit for Goddess, Shakti, and Kali-oriented Mindvanta study once the translation is cleared.',
    licenseStatus: 'needs_review',
    sourceLicenseStatus: 'unverified',
    availabilityMode: 'bibliographic_only',
    contentType: 'course_reference',
    sourceName: '1922 Swami Vijnanananda translation; reuse status pending',
    publicationYear: 1922,
    originalLanguage: 'Sanskrit',
    themes: ['Divine Feminine', 'Devotion', 'Shakti', 'Grace', 'Power'],
    tags: ['shakta', 'devi', 'divine-mother', 'shakti', 'purana'],
    courseSlug: 'goddess-shakti-and-sacred-power',
    moduleSlug: 'devi-as-cosmic-mother',
    courseReason: 'Reference point for Divine Mother and Shakti modules after license review.',
    reviewStatus: 'needs_review',
    warning: 'Do not render in production until the 1922 translation source and reuse status are approved.',
  },
];

const promptThemes = ['awareness', 'practice', 'non-attachment', 'liberation', 'integration'];

function buildReflectionPrompts(seed: PhaseOneWorkSeed) {
  return promptThemes.map((theme, index) => ({
    id: `${seed.slug}-reflection-${index + 1}`,
    sourceTextSlug: seed.slug,
    theme: seed.themes[index % seed.themes.length] ?? theme,
    prompt: `Let ${seed.title} point you toward ${theme.replace('-', ' ')} in ordinary experience today.`,
    practice: `Pause for three minutes and notice one moment where ${seed.themes[index % seed.themes.length]?.toLowerCase() ?? theme} is already present.`,
    journalQuestion: `How does ${seed.title} change the way I understand ${theme.replace('-', ' ')} today?`,
    difficulty: seed.difficultyBand,
    linkedCourseSlug: seed.courseSlug,
    linkedLibrarySlug: seed.slug,
  }));
}

export const PHASE_ONE_TEXT_WORKS: TextWork[] = phaseOneSeeds.map((seed, index) => ({
  id: seed.slug,
  slug: seed.slug,
  title_primary: seed.title,
  title_alt: seed.alternateTitles ?? [],
  author_attribution: seed.author,
  tradition: seed.tradition,
  genre: seed.genre,
  approx_date: seed.approxDate,
  difficulty: seed.difficulty,
  summary_short: seed.summary,
  summary_long: seed.summary,
  why_it_matters: seed.why,
  status_badge: seed.reviewStatus === 'needs_review' ? 'stub' : 'active',
  availability_mode: seed.availabilityMode,
  source_license_status: seed.sourceLicenseStatus,
  allowed_surfaces: ['library_card', 'study_guide', 'search_index'],
  included_in_app: [
    'Catalog metadata, source attribution, course links, and Mindvanta-original reflection prompts.',
    'No unreviewed full translation body is bundled by this metadata record.',
  ],
  not_included_yet: [
    'Unreviewed scan artifacts, Project Gutenberg boilerplate, production credits, and trademark/license wrapper text.',
    'Modern copyrighted translations or commentaries without explicit permission.',
  ],
  bibliography: [
    {
      citation: seed.sourceName,
      url: seed.sourceUrl,
      note: seed.warning,
    },
  ],
  related_text_ids: [],
  curriculum_order: 200 + index,
  tags: seed.tags,
  licenseStatus: seed.licenseStatus,
  reviewStatus: seed.reviewStatus ?? 'approved',
  contentType: seed.contentType,
  difficultyBand: seed.difficultyBand,
  originalLanguage: seed.originalLanguage,
  sourceName: seed.sourceName,
  sourceUrl: seed.sourceUrl,
  publicationYear: seed.publicationYear,
  libraryEligible: true,
  courseEligible: true,
  reflectionEligible: seed.reviewStatus !== 'needs_review',
  themes: seed.themes,
  courseLinks: [
    {
      courseSlug: seed.courseSlug,
      moduleSlug: seed.moduleSlug,
      reason: seed.courseReason,
    },
  ],
  reflectionPrompts: buildReflectionPrompts(seed),
  warning: seed.warning,
  historicalContext: seed.approxDate,
  coreTeachings: seed.themes,
  suggestedPractices: ['Read the overview slowly.', 'Use one reflection prompt for journaling.', 'Follow the linked course module.'],
}));

export const PHASE_ONE_TEXT_VERSIONS: TextVersion[] = PHASE_ONE_TEXT_WORKS.map((work) => ({
  id: `${work.slug}-metadata-v1`,
  work_id: work.id,
  language: 'English',
  translator_or_editor: work.author_attribution,
  source_name: work.sourceName,
  source_url: work.sourceUrl,
  license_type:
    work.licenseStatus === 'public_domain_us'
      ? 'public_domain_claim'
      : work.licenseStatus === 'source_text_only'
        ? 'app_original'
        : 'requires_legal_review',
  license_notes: work.warning ?? 'Metadata and Mindvanta-original prompts only; full text requires reviewed source cleanup.',
  attribution_required: true,
  commercial_use_allowed: work.licenseStatus === 'public_domain_us' || work.licenseStatus === 'open_license',
  derivative_use_allowed: work.licenseStatus === 'public_domain_us' || work.licenseStatus === 'open_license',
  approved_for_shipping: work.reviewStatus === 'approved',
  approved_surfaces: work.reviewStatus === 'approved' ? ['library_card', 'study_guide', 'search_index'] : [],
  review_notes: work.warning,
}));
