/**
 * ExplainPanel - Inline expandable panel showing AI explanation
 * 
 * Displays meaning, context, and practical application.
 */

import type { TextExplanation } from '@lib/textExplain';

type ExplainPanelProps = {
  explanation: TextExplanation;
  onClose: () => void;
};

export function ExplainPanel({ explanation, onClose }: ExplainPanelProps) {
  return (
    <div className="mt-4 bg-gradient-to-br from-amber-500/10 to-orange-500/5 rounded-xl p-4 border border-amber-500/20 animate-in fade-in slide-in-from-top-2 duration-300">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <span className="text-amber-400" aria-hidden="true">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={1.5}
                d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
              />
            </svg>
          </span>
          <span className="text-sm font-medium text-amber-300">AI Explanation</span>
        </div>
        <button
          onClick={onClose}
          className="p-1 text-white/40 hover:text-white/80 transition-colors rounded"
          title="Close explanation"
          aria-label="Close explanation"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      {/* Sections */}
      <div className="space-y-4">
        {/* Meaning */}
        <div>
          <h4 className="text-xs uppercase tracking-wider text-amber-400/70 mb-1.5 flex items-center gap-1.5">
            <span>💡</span>
            <span>Meaning</span>
          </h4>
          <p className="text-sm text-white/80 leading-relaxed">
            {explanation.meaning}
          </p>
        </div>

        {/* Context */}
        <div>
          <h4 className="text-xs uppercase tracking-wider text-amber-400/70 mb-1.5 flex items-center gap-1.5">
            <span>📜</span>
            <span>Context</span>
          </h4>
          <p className="text-sm text-white/70 leading-relaxed">
            {explanation.context}
          </p>
        </div>

        {/* Practical Application */}
        <div>
          <h4 className="text-xs uppercase tracking-wider text-amber-400/70 mb-1.5 flex items-center gap-1.5">
            <span>🎯</span>
            <span>Practical Application</span>
          </h4>
          <p className="text-sm text-white/70 leading-relaxed italic">
            {explanation.practicalApplication}
          </p>
        </div>
      </div>

      {/* Footer */}
      <div className="mt-4 pt-3 border-t border-white/10 flex items-center justify-between">
        <span className="text-xs text-white/30">
          Generated by AI • May not reflect all interpretations
        </span>
      </div>
    </div>
  );
}



